GET http://localhost:5000/api/v1/boards

###

POST http://localhost:5000/api/v1/boards/create
content-type: application/json

{
    "title": "Board 2"
}

###
DELETE http://localhost:5000/api/v1/boards
