GET http://localhost:5000/api/v1/cards

###

POST http://localhost:5000/api/v1/cards/create
content-type: application/json

{
    "title": "Card 4",
    "columnId": "64069e261bce6635ca6318aa"
}

###
DELETE http://localhost:5000/api/v1/cards
