GET http://localhost:5000/api/v1/cards

###

POST http://localhost:5000/api/v1/cards/create
content-type: application/json

{
    "title": "Card 2",
    "columnId": "640310ee7f746d03cd249948"
}

###
DELETE http://localhost:5000/api/v1/cards
