GET http://localhost:5000/api/v1/columns

###

POST http://localhost:5000/api/v1/columns/create
content-type: application/json

{
    "title": "Column 2",
    "boardId": "6403077aedf2ef1d169dcbd6"
}

###
DELETE http://localhost:5000/api/v1/columns
